# Generated by Django 4.0.5 on 2022-06-26 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_customuser_country_customuser_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='1231231231', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
