# Generated by Django 4.0.5 on 2022-06-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
